--Start--
Sun Jun 6 15:19:32 JST 2021
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "train.py", line 822, in <module>
  File "train.py", line 822, in <module>
  File "train.py", line 822, in <module>
  File "train.py", line 822, in <module>
    main()
  File "train.py", line 325, in main
    main()
  File "train.py", line 325, in main
    main()
  File "train.py", line 325, in main
    torch.cuda.set_device(args.local_rank)
  File "/gs/hs0/tga-i/sugiyama.y.al/TIMM/TIMM_386/lib/python3.8/site-packages/torch/cuda/__init__.py", line 261, in set_device
    main()
  File "train.py", line 325, in main
    torch.cuda.set_device(args.local_rank)
  File "/gs/hs0/tga-i/sugiyama.y.al/TIMM/TIMM_386/lib/python3.8/site-packages/torch/cuda/__init__.py", line 261, in set_device
    torch.cuda.set_device(args.local_rank)
  File "/gs/hs0/tga-i/sugiyama.y.al/TIMM/TIMM_386/lib/python3.8/site-packages/torch/cuda/__init__.py", line 261, in set_device
        torch._C._cuda_setDevice(device)torch._C._cuda_setDevice(device)    

torch.cuda.set_device(args.local_rank)RuntimeErrorRuntimeError
: :       File "/gs/hs0/tga-i/sugiyama.y.al/TIMM/TIMM_386/lib/python3.8/site-packages/torch/cuda/__init__.py", line 261, in set_device
CUDA error: invalid device ordinalCUDA error: invalid device ordinaltorch._C._cuda_setDevice(device)


RuntimeError: CUDA error: invalid device ordinal
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
Added key: store_based_barrier_key:1 to store for rank: 1
Added key: store_based_barrier_key:1 to store for rank: 2
Added key: store_based_barrier_key:1 to store for rank: 3
Traceback (most recent call last):
  File "/home/2/21M31163/.pyenv/versions/3.8.6/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/2/21M31163/.pyenv/versions/3.8.6/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gs/hs0/tga-i/sugiyama.y.al/TIMM/TIMM_386/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/gs/hs0/tga-i/sugiyama.y.al/TIMM/TIMM_386/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/gs/hs0/tga-i/sugiyama.y.al/TIMM/TIMM_386/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/gs/hs0/tga-i/sugiyama.y.al/TIMM/TIMM_386/bin/python', '-u', 'train.py', '--local_rank=7', './', '--pretrained', '--dataset', 'CIFAR100', '--num-classes', '100', '--model', 'vit_deit_tiny_patch16_224', '--input-size', '3', '224', '224', '--opt', 'sgd', '--batch-size', '192', '--epochs', '150', '--cooldown-epochs', '0', '--lr', '0.01', '--sched', 'cosine', '--warmup-epochs', '5', '--weight-decay', '0.0001', '--smoothing', '0.1', '--aa', 'rand-m9-mstd0.5-inc1', '--repeated-aug', '--mixup', '0.8', '--cutmix', '1.0', '--log-wandb', '--output', 'train_result', '--experiment', 'Test_Finetuning_vit_deit_tiny_patch16_224_default-imnet1k_to_CIFAR100', '--id_wandb', 'Test_Finetuning_vit_deit_tiny_patch16_224_default-imnet1k_to_CIFAR100', '-j', '4']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Killing subprocess 44203
Killing subprocess 44204
Killing subprocess 44205
Killing subprocess 44206
Killing subprocess 44207
Killing subprocess 44208
Killing subprocess 44209
Killing subprocess 44210
--End--
Sun Jun 6 15:20:29 JST 2021
